package com.jwebmp.website.pages.frameworks;

import com.jwebmp.core.base.angular.client.annotations.angular.NgComponent;
import com.jwebmp.core.base.angular.client.annotations.routing.NgRoutable;
import com.jwebmp.website.catalog.PluginCatalog;
import com.jwebmp.website.catalog.PluginEntry;

import java.util.List;

@NgComponent("jwebmp-framework-jquery-ui")
@NgRoutable(path = "frameworks/jquery-ui")
public class JQueryUIFrameworkPage extends FrameworkDetailPage<JQueryUIFrameworkPage>
{
    public static final List<PluginEntry.ComponentInfo> COMPONENTS = List.of(
            new PluginEntry.ComponentInfo("JQUIAccordion",
                    "Collapsible content panels for presenting information in a limited amount of space. Supports animation, easing, icons, and height styles.",
                    "com.jwebmp.plugins.jqueryui.accordion",
                    List.of(
                            new PluginEntry.PropertyInfo("heightStyle", "JQUIAccordionHeightStyle", "auto", "Controls panel height: auto, fill, or content"),
                            new PluginEntry.PropertyInfo("collapsible", "boolean", "false", "Allow all panels to be closed"),
                            new PluginEntry.PropertyInfo("active", "int", "0", "Index of the initially active panel"),
                            new PluginEntry.PropertyInfo("animate", "boolean", "true", "Enable open/close animation")
                    ),
                    List.of(new PluginEntry.ExampleSnippet("Basic Accordion", "Create a collapsible accordion.",
                            "var accordion = new JQUIAccordion<>();\nvar tab = new JQUIAccordionTab<>(\"Section 1\", new Div<>().setText(\"Content\"));\naccordion.addAccordionTab(tab);", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIAccordion&lt;&gt;()", "Creates a default accordion"),
                            new PluginEntry.ConstructorInfo("new JQUIAccordion&lt;&gt;(JQUIAccordionHeightStyle heightStyle)", "Creates with a height style")),
                    List.of(new PluginEntry.MethodInfo("addAccordionTab", "J", "addAccordionTab(JQUIAccordionTab&lt;?&gt; tab)", "Adds a tab to the accordion"),
                            new PluginEntry.MethodInfo("getOptions", "JQUIAccordionOptions&lt;?&gt;", "getOptions()", "Returns the accordion options")),
                    List.of(), List.of(), List.of("JQUIAccordionChildren")),
            new PluginEntry.ComponentInfo("JQUIAutoComplete",
                    "Text input with filtered suggestions from local or AJAX data sources.",
                    "com.jwebmp.plugins.jqueryui.autocomplete",
                    List.of(), List.of(new PluginEntry.ExampleSnippet("Autocomplete", "Create an autocomplete input.",
                            "var auto = new JQUIAutoComplete<>();\nauto.getOptions().setSource(List.of(\"Java\", \"JavaScript\", \"Python\"));", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIAutoComplete&lt;&gt;()", "Creates an autocomplete input")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUIAutoCompleteOptions&lt;?&gt;", "getOptions()", "Returns the autocomplete options")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUIButton",
                    "Enhanced buttons and button sets with icon support. Pre-styled variants include primary, secondary, and icon-only.",
                    "com.jwebmp.plugins.jqueryui.button",
                    List.of(),
                    List.of(new PluginEntry.ExampleSnippet("Icon Button", "Create a button with an icon.",
                            "var btn = new JQUIButton<>(\"Save\");\nbtn.getOptions().setIcons(new JQUIButtonIcon(\"ui-icon-disk\"));", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIButton&lt;&gt;()", "Creates a default button"),
                            new PluginEntry.ConstructorInfo("new JQUIButton&lt;&gt;(String text)", "Creates a button with label text")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUIButtonOptions&lt;?&gt;", "getOptions()", "Returns the button options")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUICheckBoxGroup",
                    "Checkbox group with styled checkbox inputs using the jQuery UI checkboxradio widget.",
                    "com.jwebmp.plugins.jqueryui.checkboxradio",
                    List.of(), List.of(new PluginEntry.ExampleSnippet("Checkbox Group", "Create styled checkboxes.",
                            "var group = new JQUICheckBoxGroup<>();\ngroup.addCheckBox(\"Option A\", \"a\");\ngroup.addCheckBox(\"Option B\", \"b\");", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUICheckBoxGroup&lt;&gt;()", "Creates a checkbox group")),
                    List.of(), List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUIDatePicker",
                    "Full-featured date selection with popup or inline calendar, localization, date ranges, and format options.",
                    "com.jwebmp.plugins.jqueryui.datepicker",
                    List.of(new PluginEntry.PropertyInfo("dateFormat", "String", "mm/dd/yy", "The format for parsed and displayed dates"),
                            new PluginEntry.PropertyInfo("changeMonth", "boolean", "false", "Show month dropdown"),
                            new PluginEntry.PropertyInfo("changeYear", "boolean", "false", "Show year dropdown"),
                            new PluginEntry.PropertyInfo("numberOfMonths", "int", "1", "Number of months to display")),
                    List.of(new PluginEntry.ExampleSnippet("Date Picker", "Create a date picker.",
                            "var dp = new JQUIDatePicker<>();\ndp.getOptions().setDateFormat(\"yy-mm-dd\");\ndp.getOptions().setChangeMonth(true);\ndp.getOptions().setChangeYear(true);", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIDatePicker&lt;&gt;()", "Creates a date picker with today's date"),
                            new PluginEntry.ConstructorInfo("new JQUIDatePicker&lt;&gt;(Date selectedDate)", "Creates with a pre-selected date")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUIDatePickerOptions&lt;?&gt;", "getOptions()", "Returns the date picker options")),
                    List.of(), List.of(), List.of("IJQUIDatePicker")),
            new PluginEntry.ComponentInfo("JQUIDialog",
                    "Modal and modeless dialog boxes with title bar, positioning, resizing, and close button. Supports buttons, animations, and overlay backdrop.",
                    "com.jwebmp.plugins.jqueryui.dialog",
                    List.of(new PluginEntry.PropertyInfo("modal", "boolean", "false", "Display as a modal dialog with overlay"),
                            new PluginEntry.PropertyInfo("draggable", "boolean", "true", "Allow the dialog to be dragged"),
                            new PluginEntry.PropertyInfo("resizable", "boolean", "true", "Allow the dialog to be resized"),
                            new PluginEntry.PropertyInfo("width", "int", "300", "Width of the dialog in pixels"),
                            new PluginEntry.PropertyInfo("height", "int", "auto", "Height of the dialog")),
                    List.of(new PluginEntry.ExampleSnippet("Modal Dialog", "Create a modal dialog.",
                            "var dialog = new JQUIDialog<>(\"Confirm\");\ndialog.getOptions().setModal(true);\ndialog.getOptions().setWidth(400);\ndialog.setText(\"Are you sure?\");", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIDialog&lt;&gt;(String title)", "Creates a dialog with the given title")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUIDialogOptions&lt;?&gt;", "getOptions()", "Returns the dialog options")),
                    List.of(), List.of(), List.of("IJQUIDialog")),
            new PluginEntry.ComponentInfo("JQUIDraggable",
                    "Make any DOM element draggable with mouse. Supports containment, snapping to grid, axis constraints, and cursor styles.",
                    "com.jwebmp.plugins.jqueryui.draggable",
                    List.of(new PluginEntry.PropertyInfo("axis", "String", "null", "Constrain dragging to x or y axis"),
                            new PluginEntry.PropertyInfo("containment", "String", "null", "Constrains dragging to within a parent or selector"),
                            new PluginEntry.PropertyInfo("grid", "int[]", "null", "Snap to grid [x, y] in pixels")),
                    List.of(new PluginEntry.ExampleSnippet("Draggable Element", "Make a div draggable.",
                            "var box = new JQUIDraggable<>();\nbox.setText(\"Drag me!\");\nbox.getOptions().setAxis(\"x\");", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIDraggable&lt;&gt;()", "Creates a draggable element")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUIDraggableOptions&lt;?&gt;", "getOptions()", "Returns the draggable options")),
                    List.of(), List.of(), List.of("IJQUIDraggable")),
            new PluginEntry.ComponentInfo("JQUIDroppable",
                    "Define drop targets for draggable elements. Supports accept filtering, tolerance modes, and visual feedback.",
                    "com.jwebmp.plugins.jqueryui.droppable",
                    List.of(new PluginEntry.PropertyInfo("accept", "String", "*", "Selector to filter which draggables are accepted"),
                            new PluginEntry.PropertyInfo("tolerance", "String", "intersect", "Tolerance mode: fit, intersect, pointer, touch")),
                    List.of(new PluginEntry.ExampleSnippet("Droppable Target", "Create a drop target.",
                            "var target = new JQUIDroppable<>();\ntarget.setText(\"Drop here\");\ntarget.getOptions().setAccept(\".draggable\");", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIDroppable&lt;&gt;()", "Creates a droppable target")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUIDroppableOptions&lt;?&gt;", "getOptions()", "Returns the droppable options")),
                    List.of(), List.of(), List.of("IJQUIDroppable")),
            new PluginEntry.ComponentInfo("JQUIMenu",
                    "Themeable menu with keyboard navigation, mouse interaction, and nested sub-menus.",
                    "com.jwebmp.plugins.jqueryui.menu",
                    List.of(),
                    List.of(new PluginEntry.ExampleSnippet("Menu", "Create a themed menu.",
                            "var menu = new JQUIMenu<>();\nmenu.addItem(\"Open\");\nmenu.addItem(\"Save\");\nmenu.addItem(\"Close\");", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIMenu&lt;&gt;()", "Creates a menu")),
                    List.of(new PluginEntry.MethodInfo("addItem", "J", "addItem(String text)", "Adds a menu item")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUIProgressBar",
                    "Determinate and indeterminate progress indicators with percentage display and value animation.",
                    "com.jwebmp.plugins.jqueryui.progressbar",
                    List.of(new PluginEntry.PropertyInfo("value", "int", "0", "Current progress value (0-100)"),
                            new PluginEntry.PropertyInfo("max", "int", "100", "Maximum progress value")),
                    List.of(new PluginEntry.ExampleSnippet("Progress Bar", "Create a progress bar.",
                            "var bar = new JQUIProgressBar<>();\nbar.getOptions().setValue(75);", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIProgressBar&lt;&gt;()", "Creates a progress bar")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUIProgressBarOptions&lt;?&gt;", "getOptions()", "Returns the progress bar options")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUIResizable",
                    "Make elements resizable with drag handles. Supports aspect ratio preservation, min/max constraints, and ghost preview.",
                    "com.jwebmp.plugins.jqueryui.resizable",
                    List.of(new PluginEntry.PropertyInfo("aspectRatio", "boolean", "false", "Preserve aspect ratio while resizing"),
                            new PluginEntry.PropertyInfo("ghost", "boolean", "false", "Show a semi-transparent helper while resizing"),
                            new PluginEntry.PropertyInfo("handles", "String", "e, s, se", "Which handles to enable")),
                    List.of(new PluginEntry.ExampleSnippet("Resizable Element", "Make an element resizable.",
                            "var box = new JQUIResizable<>();\nbox.setText(\"Resize me\");\nbox.getOptions().setAspectRatio(true);", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUIResizable&lt;&gt;()", "Creates a resizable element")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUIResizableOptions&lt;?&gt;", "getOptions()", "Returns the resizable options")),
                    List.of(), List.of(), List.of("IJQUIResizable")),
            new PluginEntry.ComponentInfo("JQUISelectable",
                    "Lasso-selection for groups of elements. Click and drag to select multiple items.",
                    "com.jwebmp.plugins.jqueryui.selectable",
                    List.of(new PluginEntry.PropertyInfo("tolerance", "String", "touch", "Tolerance mode: fit or touch")),
                    List.of(new PluginEntry.ExampleSnippet("Selectable List", "Create a selectable list.",
                            "var list = new JQUISelectable<>();\nlist.addItem(\"Item 1\");\nlist.addItem(\"Item 2\");\nlist.addItem(\"Item 3\");", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUISelectable&lt;&gt;()", "Creates a selectable container")),
                    List.of(), List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUISelectMenu",
                    "Styled dropdown replacement extending the native HTML select with theming, icons, and overflow handling.",
                    "com.jwebmp.plugins.jqueryui.selectmenu",
                    List.of(),
                    List.of(new PluginEntry.ExampleSnippet("Select Menu", "Create a styled select.",
                            "var select = new JQUISelectMenu<>();\nselect.addOption(\"Option 1\", \"1\");\nselect.addOption(\"Option 2\", \"2\");", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUISelectMenu&lt;&gt;()", "Creates a select menu")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUISelectMenuOptions&lt;?&gt;", "getOptions()", "Returns the select menu options")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUISlider",
                    "Range and value sliders with steps, min/max, and orientation. Supports single value or range selection.",
                    "com.jwebmp.plugins.jqueryui.slider",
                    List.of(new PluginEntry.PropertyInfo("min", "int", "0", "Minimum slider value"),
                            new PluginEntry.PropertyInfo("max", "int", "100", "Maximum slider value"),
                            new PluginEntry.PropertyInfo("step", "int", "1", "Step increment"),
                            new PluginEntry.PropertyInfo("orientation", "String", "horizontal", "Slider orientation: horizontal or vertical"),
                            new PluginEntry.PropertyInfo("range", "boolean", "false", "Enable range selection with two handles")),
                    List.of(new PluginEntry.ExampleSnippet("Range Slider", "Create a range slider.",
                            "var slider = new JQUISlider<>();\nslider.getOptions().setMin(0);\nslider.getOptions().setMax(500);\nslider.getOptions().setRange(true);", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUISlider&lt;&gt;()", "Creates a slider")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUISliderOptions&lt;?&gt;", "getOptions()", "Returns the slider options")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUISortable",
                    "Reorderable lists with drag-and-drop. Supports connected lists, placeholders, and axis constraints.",
                    "com.jwebmp.plugins.jqueryui.sortable",
                    List.of(new PluginEntry.PropertyInfo("placeholder", "String", "null", "CSS class for the drop placeholder"),
                            new PluginEntry.PropertyInfo("axis", "String", "null", "Constrain sorting to x or y axis"),
                            new PluginEntry.PropertyInfo("connectWith", "String", "null", "Selector of other sortable lists to connect")),
                    List.of(new PluginEntry.ExampleSnippet("Sortable List", "Create a sortable list.",
                            "var list = new JQUISortable<>();\nlist.addItem(\"Item A\");\nlist.addItem(\"Item B\");\nlist.addItem(\"Item C\");", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUISortable&lt;&gt;()", "Creates a sortable container")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUISortableOptions&lt;?&gt;", "getOptions()", "Returns the sortable options")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUISpinner",
                    "Numeric input with increment/decrement buttons. Supports step, min, max, number format, and page stepping.",
                    "com.jwebmp.plugins.jqueryui.spinner",
                    List.of(new PluginEntry.PropertyInfo("min", "int", "null", "Minimum allowed value"),
                            new PluginEntry.PropertyInfo("max", "int", "null", "Maximum allowed value"),
                            new PluginEntry.PropertyInfo("step", "int", "1", "Step increment for each click"),
                            new PluginEntry.PropertyInfo("page", "int", "10", "Number of steps for page up/down")),
                    List.of(new PluginEntry.ExampleSnippet("Spinner", "Create a numeric spinner.",
                            "var spinner = new JQUISpinner<>();\nspinner.getOptions().setMin(0);\nspinner.getOptions().setMax(100);\nspinner.getOptions().setStep(5);", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUISpinner&lt;&gt;()", "Creates a spinner input")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUISpinnerOptions&lt;?&gt;", "getOptions()", "Returns the spinner options")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUITabs",
                    "Tabbed content panels. Supports collapsible tabs, events, AJAX loading, and sortable tabs.",
                    "com.jwebmp.plugins.jqueryui.tabs",
                    List.of(new PluginEntry.PropertyInfo("collapsible", "boolean", "false", "Allow all tabs to be closed"),
                            new PluginEntry.PropertyInfo("active", "int", "0", "Index of the initially active tab")),
                    List.of(new PluginEntry.ExampleSnippet("Tabbed Panels", "Create tabbed content.",
                            "var tabs = new JQUITabs<>();\ntabs.addTab(\"Tab 1\", new Div<>().setText(\"Content 1\"));\ntabs.addTab(\"Tab 2\", new Div<>().setText(\"Content 2\"));", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUITabs&lt;&gt;()", "Creates a tabbed container")),
                    List.of(new PluginEntry.MethodInfo("addTab", "J", "addTab(String title, Component content)", "Adds a tab with title and content"),
                            new PluginEntry.MethodInfo("getOptions", "JQUITabsOptions&lt;?&gt;", "getOptions()", "Returns the tabs options")),
                    List.of(), List.of(), List.of()),
            new PluginEntry.ComponentInfo("JQUITooltip",
                    "Configurable tooltips replacing native browser tooltips. Supports positioning, content customization, and animation.",
                    "com.jwebmp.plugins.jqueryui.tooltip",
                    List.of(new PluginEntry.PropertyInfo("track", "boolean", "false", "Tooltip follows the mouse"),
                            new PluginEntry.PropertyInfo("position", "Object", "null", "Position configuration (my, at, of, collision)")),
                    List.of(new PluginEntry.ExampleSnippet("Tooltip", "Add a tooltip to an element.",
                            "var tip = new JQUITooltip<>();\ntip.getOptions().setContent(\"Helpful information\");\ntip.getOptions().setTrack(true);", "java")),
                    List.of(new PluginEntry.ConstructorInfo("new JQUITooltip&lt;&gt;()", "Creates a tooltip")),
                    List.of(new PluginEntry.MethodInfo("getOptions", "JQUITooltipOptions&lt;?&gt;", "getOptions()", "Returns the tooltip options")),
                    List.of(), List.of(), List.of())
    );

    public JQueryUIFrameworkPage()
    {
        super(PluginCatalog.getById("jquery-ui").orElseThrow());
    }

    @Override
    protected String frameworkId()
    {
        return "jquery-ui";
    }

    @Override
    protected List<PluginEntry.ComponentInfo> frameworkComponents()
    {
        return COMPONENTS;
    }
}

